export const shoes = [
  {
    id: 1,
    url: 'https://www.amazon.co.uk/dp/B08BLP231K',
    title: 'Geox Jr Sandal Strada B Fisherman, Brown Red, 2.5 UK Child',
    price: 29.75,
    brand: 'Visit the Geox Store',
    categoryId: 3,
    images: [
      'https://m.media-amazon.com/images/I/41OuvqjhaqL.jpg',
      'https://m.media-amazon.com/images/I/51zt+Bb48FL.jpg',
      'https://m.media-amazon.com/images/I/51EXdVtkpAL.jpg',
      'https://m.media-amazon.com/images/I/41u3T2DxWkL.jpg',
      'https://m.media-amazon.com/images/I/41ZOt3pgbSL.jpg',
      'https://m.media-amazon.com/images/I/41FEYlXQNFL.jpg',
      'https://m.media-amazon.com/images/I/41Nqt4ULBUL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Strap',
      'heel Height': '2 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 2,
    url: 'https://www.amazon.co.uk/dp/B08N587YZ9',
    title: "Fila Women's Oakmont Tr Sneaker",
    price: 58.81,
    brand: 'Fila',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/416fCMuxwLL.jpg',
      'https://m.media-amazon.com/images/I/51mkH58Ym8L.jpg',
      'https://m.media-amazon.com/images/I/51FOdSMTzHL.jpg',
      'https://m.media-amazon.com/images/I/41nDJ-+mwBL.jpg',
      'https://m.media-amazon.com/images/I/41EEIOcPNKL.jpg',
      'https://m.media-amazon.com/images/I/416y8+Qzp2L.jpg',
      'https://m.media-amazon.com/images/I/41STmbB8njL.jpg',
    ],
    features: {
      'outer Material': 'fabric',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'medium',
    },
  },
  {
    id: 3,
    url: 'https://www.amazon.co.uk/dp/B0918K4H1W',
    title:
      "Gabor Rollingsoft Trainers in Plus Sizes Beige 66.938.30 Large Women's Shoes",
    price: 86.51,
    brand: 'Gabor',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31GuoIF6FmL.jpg',
      'https://m.media-amazon.com/images/I/317PRDRbPRL.jpg',
      'https://m.media-amazon.com/images/I/31WCZ3IunBL.jpg',
      'https://m.media-amazon.com/images/I/31GzfcPERSL.jpg',
      'https://m.media-amazon.com/images/I/31HTleJH3bL.jpg',
      'https://m.media-amazon.com/images/I/31lkVAeCMeL.jpg',
      'https://m.media-amazon.com/images/I/412zP242i+L.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      sole: 'Leather',
      closure: 'Lace-Up',
      'shoe Width': 'Schmal',
    },
  },
  {
    id: 4,
    url: 'https://www.amazon.co.uk/dp/B07KMB98CG',
    title: "Merrell Women'S Bare Access Xtr Trail Running Shoes",
    price: 61.98,
    brand: 'Visit the Merrell Store',
    categoryId: 9,
    images: [
      'https://m.media-amazon.com/images/I/51bLpccQMkL.jpg',
      'https://m.media-amazon.com/images/I/51X3qFZUIxL.jpg',
      'https://m.media-amazon.com/images/I/51MQseoK7RL.jpg',
      'https://m.media-amazon.com/images/I/41aDt5XRu8L.jpg',
      'https://m.media-amazon.com/images/I/41us9YGUh2L.jpg',
      'https://m.media-amazon.com/images/I/41qdx8YsT9L.jpg',
      'https://m.media-amazon.com/images/I/41d-HO03K4L.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 5,
    url: 'https://www.amazon.co.uk/dp/B08CN3S1ZK',
    title: "Desigual Women's Shoes_Runner_cmofl Sneakers Woman",
    price: 88.95,
    brand: 'Desigual',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41nMmmxX-oL.jpg',
      'https://m.media-amazon.com/images/I/413yrw6izSL.jpg',
      'https://m.media-amazon.com/images/I/51GYDvFInuL.jpg',
      'https://m.media-amazon.com/images/I/41XLBSGfhpL.jpg',
      'https://m.media-amazon.com/images/I/41ce6h+LkfL.jpg',
      'https://m.media-amazon.com/images/I/410n1HdmoWL.jpg',
      'https://m.media-amazon.com/images/I/41Sw5OMEECL.jpg',
    ],
    features: {
      'outer Material': 'Polyester',
      'inner Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 6,
    url: 'https://www.amazon.co.uk/dp/B07KJX15DV',
    title: "Aquatalia Men's Adamo Dress Calf Penny Loafer",
    price: 97.08,
    brand: 'Aquatalia',
    categoryId: 11,
    images: [
      'https://m.media-amazon.com/images/I/31Q2dvpJryL.jpg',
      'https://m.media-amazon.com/images/I/41uTxM9VBHL.jpg',
      'https://m.media-amazon.com/images/I/41ynI5DMZnL.jpg',
      'https://m.media-amazon.com/images/I/21WOABMNIAL.jpg',
      'https://m.media-amazon.com/images/I/319g5-RTshL.jpg',
      'https://m.media-amazon.com/images/I/317ji9LWSKL.jpg',
      'https://m.media-amazon.com/images/I/31aJwmaFbSL.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Pull On',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 7,
    url: 'https://www.amazon.co.uk/dp/B089GYT1HP',
    title: 'Womens Convertible Slip-on, Tan, 12',
    price: 90.11,
    brand: 'Unknown',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31cusYt00VL.jpg',
      'https://m.media-amazon.com/images/I/419AtRU0DNL.jpg',
      'https://m.media-amazon.com/images/I/41N7jkd4zHL.jpg',
      'https://m.media-amazon.com/images/I/31zkJ8SGGDL.jpg',
      'https://m.media-amazon.com/images/I/31PP+ISFQgL.jpg',
      'https://m.media-amazon.com/images/I/31Shj6UpzDL.jpg',
      'https://m.media-amazon.com/images/I/41iLkwMwMFL.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Pull On',
      'heel Type': 'Low',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 8,
    url: 'https://www.amazon.co.uk/dp/B01614251K',
    title: "Kappa Delhi Footwear Unisex, Mesh, Women's Low-Top Sneakers",
    price: 69.89,
    brand: 'Visit the Kappa Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41MfJGQsSBL.jpg',
      'https://m.media-amazon.com/images/I/519qDn3yq-L.jpg',
      'https://m.media-amazon.com/images/I/41rCXl8bBcL.jpg',
      'https://m.media-amazon.com/images/I/31Acajc-xYL.jpg',
      'https://m.media-amazon.com/images/I/413wcLbldIL.jpg',
      'https://m.media-amazon.com/images/I/41Pi0Vfo+QL.jpg',
      'https://m.media-amazon.com/images/I/41e05YNjCrL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Mesh',
      sole: 'Manmade',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 9,
    url: 'https://www.amazon.co.uk/dp/B07MJ4DRRZ',
    title: "Naturalizer Women's Cairo 4 Sneaker, Medium",
    price: 46.22,
    brand: 'Naturalizer',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31B+IfyybEL.jpg',
      'https://m.media-amazon.com/images/I/41nARY0TYlL.jpg',
      'https://m.media-amazon.com/images/I/41MhfjmosPL.jpg',
      'https://m.media-amazon.com/images/I/31Sfx9bndiL.jpg',
      'https://m.media-amazon.com/images/I/31k+FmRm1hL.jpg',
      'https://m.media-amazon.com/images/I/31QdigB4GPL.jpg',
      'https://m.media-amazon.com/images/I/41S6ADRTfyL.jpg',
    ],
    features: {
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'shoe Width': 'M',
    },
  },
  {
    id: 10,
    url: 'https://www.amazon.co.uk/dp/B07GX8GPJN',
    title: 'Rockport - Womens Cobb Hill Hattie Hi Cuff Platform Shoe',
    price: 98.95,
    brand: 'Visit the Rockport Store',
    categoryId: 12,
    images: ['https://m.media-amazon.com/images/I/51H4VpBqujL.jpg'],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Leather, Ethylene Vinyl Acetate',
      closure: 'Buckle',
      'heel Type': 'Wedge',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 11,
    url: 'https://www.amazon.co.uk/dp/B012DS5U2Y',
    title: "Reebok Men's NPC Ii Fashion Sneaker",
    price: 89.48,
    brand: 'Visit the Reebok Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/31Q5ITz9A1L.jpg',
      'https://m.media-amazon.com/images/I/31zTqnl8B1L.jpg',
      'https://m.media-amazon.com/images/I/31cJeqWHkXL.jpg',
      'https://m.media-amazon.com/images/I/31VChOZlUvL.jpg',
      'https://m.media-amazon.com/images/I/31tZwWe46cL.jpg',
      'https://m.media-amazon.com/images/I/312gwJ-AfwL.jpg',
      'https://m.media-amazon.com/images/I/31aftLNUgNL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Normal',
    },
  },
  {
    id: 12,
    url: 'https://www.amazon.co.uk/dp/B08D3F9JQY',
    title: "adidas Women's Superstar Bold W Gymnastics Shoe",
    price: 85.08,
    brand: 'Visit the adidas Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31iEsAXEKWL.jpg',
      'https://m.media-amazon.com/images/I/31ebhXvIqUL.jpg',
      'https://m.media-amazon.com/images/I/31srq7sW-gL.jpg',
      'https://m.media-amazon.com/images/I/31yVdG+11LL.jpg',
      'https://m.media-amazon.com/images/I/3181dSfKKHL.jpg',
    ],
    features: {
      'outer Material': 'Smooth Leather',
      'inner Material': 'Textile',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'material Composition': 'Leather upper, textile lining, rubber outsole',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 13,
    url: 'https://www.amazon.co.uk/dp/B01GRUZWAO',
    title: "Geox Women's D Sfinge a Fashion Sneaker",
    price: 88.11,
    brand: 'Visit the Geox Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41nClsGThtL.jpg',
      'https://m.media-amazon.com/images/I/41wk9QjiMnL.jpg',
      'https://m.media-amazon.com/images/I/41BPdM1ttRL.jpg',
      'https://m.media-amazon.com/images/I/41bb40A9iYL.jpg',
      'https://m.media-amazon.com/images/I/41u0DuohyDL.jpg',
      'https://m.media-amazon.com/images/I/41wZ7aDasSL.jpg',
      'https://m.media-amazon.com/images/I/41qjIMKAX+L.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Mesh',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Lace-Up',
      'heel Height': '3.5 centimetres',
      'heel Type': 'Flat',
      'fit Type':
        'Bear in mind that Geox shoes have a comfortable fit, therefore we recommend choosing half a size smaller than your usual size',
      'shoe Width': 'Medium womens_us',
    },
  },
  {
    id: 14,
    url: 'https://www.amazon.co.uk/dp/B07SQ5MLXZ',
    title: "K-Swiss Men's Clean Court Ii CMF Low-Top Sneakers",
    price: 62.84,
    brand: 'K-Swiss',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/31TbwQNbqTL.jpg',
      'https://m.media-amazon.com/images/I/312ugppuUQL.jpg',
      'https://m.media-amazon.com/images/I/315Hd+zudEL.jpg',
      'https://m.media-amazon.com/images/I/31EN035Dx1L.jpg',
      'https://m.media-amazon.com/images/I/31nQDiC785L.jpg',
      'https://m.media-amazon.com/images/I/31SkaYKTSiL.jpg',
      'https://m.media-amazon.com/images/I/31dF8pmbJSL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Synthetic Fur',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 15,
    url: 'https://www.amazon.co.uk/dp/B00LIHRNQI',
    title: 'Volcom Mens Sub Zero Boot Winter',
    price: 44.58,
    brand: 'Visit the Volcom Store',
    categoryId: 15,
    images: [
      'https://m.media-amazon.com/images/I/41TcKadAqZL.jpg',
      'https://m.media-amazon.com/images/I/41dWg0GyQuL.jpg',
      'https://m.media-amazon.com/images/I/416vBj9KjeL.jpg',
      'https://m.media-amazon.com/images/I/41yOvHyIO-L.jpg',
      'https://m.media-amazon.com/images/I/31jgngm5seL.jpg',
      'https://m.media-amazon.com/images/I/411YkOaHu9L.jpg',
      'https://m.media-amazon.com/images/I/41M9cYZEGlL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 16,
    url: 'https://www.amazon.co.uk/dp/B07H3XFPR9',
    title: 'ASICS Mens Gel-Ziruss 2 Running Shoes Carbon/Black',
    price: 70.1,
    brand: 'ASICS',
    categoryId: 18,
    images: [
      'https://m.media-amazon.com/images/I/419SXtgq6EL.jpg',
      'https://m.media-amazon.com/images/I/51znFjH+w1L.jpg',
      'https://m.media-amazon.com/images/I/51MoaCTJ6cL.jpg',
      'https://m.media-amazon.com/images/I/413etqCs0LL.jpg',
      'https://m.media-amazon.com/images/I/4180U+paIJL.jpg',
      'https://m.media-amazon.com/images/I/4183Ca27wvL.jpg',
      'https://m.media-amazon.com/images/I/51MFLeT+aCL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 17,
    url: 'https://www.amazon.co.uk/dp/B07KQKYZYR',
    title: "bugatti Women's 432636065969 Low-Top Sneakers",
    price: 50.38,
    brand: 'bugatti',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41exUG2FL5L.jpg',
      'https://m.media-amazon.com/images/I/41StjshFK0L.jpg',
      'https://m.media-amazon.com/images/I/41ggTW58phL.jpg',
      'https://m.media-amazon.com/images/I/319IwX8smdL.jpg',
      'https://m.media-amazon.com/images/I/31cVvjVBORL.jpg',
      'https://m.media-amazon.com/images/I/31ziXpu7AtL.jpg',
      'https://m.media-amazon.com/images/I/41x89YYyJKL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Textile',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 18,
    url: 'https://www.amazon.co.uk/dp/B08HJJ5N7R',
    title: "Pablosky Girl's 495000 Sandal",
    price: 49.87,
    brand: 'Pablosky',
    categoryId: 20,
    images: [
      'https://m.media-amazon.com/images/I/31lTfKx5r0L.jpg',
      'https://m.media-amazon.com/images/I/31AJQc5sE9L.jpg',
      'https://m.media-amazon.com/images/I/31fUSsDPl+L.jpg',
      'https://m.media-amazon.com/images/I/31MnM8uWBUL.jpg',
      'https://m.media-amazon.com/images/I/31IHqiry2JL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      sole: 'Rubber',
      closure: 'Hook & Loop',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 19,
    url: 'https://www.amazon.co.uk/dp/B08635QDSF',
    title:
      'HROYL Girls Dance Shoes Satin Latin/Chacha/Samba/Modern/Jazz Dance Shoes Ballroom 206',
    price: 117.72,
    brand: 'Visit the HROYL Store',
    categoryId: 21,
    images: [
      'https://m.media-amazon.com/images/I/41u3nswtlAL.jpg',
      'https://m.media-amazon.com/images/I/41+6R69avQL.jpg',
      'https://m.media-amazon.com/images/I/51ZZf46pd2L.jpg',
      'https://m.media-amazon.com/images/I/511Wct8kR9L.jpg',
      'https://m.media-amazon.com/images/I/51MuvpcOhOL.jpg',
      'https://m.media-amazon.com/images/I/51-7HmsLJLL.jpg',
      'https://m.media-amazon.com/images/I/51BgT0jdDTL.jpg',
    ],
    features: {
      Comfortable:
        'The angle between the toe and the bottom is 15 degrees, which makes the dance movement easier to move forward or backward.Make the shoes comfort and flexibility.',
      'outer Material': 'Satin',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Buckle',
      'heel Height': '3.5 centimetres',
      'heel Type': 'Block',
      'material Composition': 'satin & gliter leather',
      'shaft Diameter': 'Medium',
      'shoe Width': 'Normal',
      'SOFT LIGHTWEIGHT':
        'Super lightweight and flexible, make you feel great freedom and comfortable in wearing, keep your amazing dancing..',
      OCCASION:
        'indoor/outdoor ballroom dance such as salsa, quickstep, latin, waltz, foxtrot, rumba, cha cha, swing, disco, samba, jive,tango or some other special occasion such as wedding ,party or dance training center ,etc. .',
      'SIZE TIP':
        'Dance shoes are different from ordinary sports shoes. It needs high comfort, Please measure the length and width of your feet before purchase , then refer to our size chart for shopping. If your feet is a little wide please choose a bigger size..',
    },
  },
  {
    id: 20,
    url: 'https://www.amazon.co.uk/dp/B084GB1DS3',
    title: "MILLET Unisex's Hike Up Mid GTX Slouch Boots",
    price: 86.99,
    brand: 'Visit the MILLET Store',
    categoryId: 23,
    images: [
      'https://m.media-amazon.com/images/I/416WiewUFJL.jpg',
      'https://m.media-amazon.com/images/I/41MY+GGjalL.jpg',
      'https://m.media-amazon.com/images/I/31YudpqSf2L.jpg',
      'https://m.media-amazon.com/images/I/31ixnfV7RDL.jpg',
      'https://m.media-amazon.com/images/I/31NK6jfGgLL.jpg',
      'https://m.media-amazon.com/images/I/41nVlfSNfvL.jpg',
      'https://m.media-amazon.com/images/I/41ixMjy3eEL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Manmade',
      sole: 'Bast',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
      contents: 'Castle Gray (Light Gray)',
    },
  },
  {
    id: 21,
    url: 'https://www.amazon.co.uk/dp/B07T26WQF5',
    title: "adidas Originals Men's Superstar Foundation Sneaker",
    price: 26.21,
    brand: 'adidas Originals',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/31PV8FxA9hL.jpg',
      'https://m.media-amazon.com/images/I/31rM6XZH+mL.jpg',
      'https://m.media-amazon.com/images/I/31TK9uSOD8L.jpg',
      'https://m.media-amazon.com/images/I/31O-VlY70-L.jpg',
      'https://m.media-amazon.com/images/I/31JvxRZkABL.jpg',
      'https://m.media-amazon.com/images/I/31srUKGhBlL.jpg',
      'https://m.media-amazon.com/images/I/31ZDmA7TNoL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'material Composition': 'Leather',
      'shoe Width': 'Normale',
    },
  },
  {
    id: 22,
    url: 'https://www.amazon.co.uk/dp/B0824F5JRM',
    title: "victoria Women's Tenis Piel/Virutas Glitter Sneaker",
    price: 88.94,
    brand: 'VICTORIA',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41EgRWMfFGL.jpg',
      'https://m.media-amazon.com/images/I/41V4o765pqL.jpg',
      'https://m.media-amazon.com/images/I/51R1wrMDoRL.jpg',
      'https://m.media-amazon.com/images/I/41XQjybB3GL.jpg',
      'https://m.media-amazon.com/images/I/31Iapx2LA1L.jpg',
      'https://m.media-amazon.com/images/I/31sRczUvUYL.jpg',
      'https://m.media-amazon.com/images/I/41Z+ixc5vuL.jpg',
    ],
    features: {
      'outer Material': 'Smooth Leather',
      'inner Material': 'Canvas',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'Low',
      'shoe Width': 'Medium',
      'shoe width': 'medium.',
    },
  },
  {
    id: 23,
    url: 'https://www.amazon.co.uk/dp/B08XJG46Q4',
    title:
      "ZYLDK Garden Shoes Children's Unisex Clogs Children's Bathing Shoes Hollow Mules Non-Slip Slippers with Cartoon Frog Bee Pink Size:",
    price: 55.29,
    brand: 'ZYLDK',
    categoryId: -1,
    images: [
      'https://m.media-amazon.com/images/I/4182E9SwDNL.jpg',
      'https://m.media-amazon.com/images/I/410NfxsnsZL.jpg',
      'https://m.media-amazon.com/images/I/41bETJE1RkL.jpg',
      'https://m.media-amazon.com/images/I/41Xi765CdwL.jpg',
      'https://m.media-amazon.com/images/I/41ar6Ndms7L.jpg',
      'https://m.media-amazon.com/images/I/51oWjNFA4RL.jpg',
      'https://m.media-amazon.com/images/I/417CPF0LP1L.jpg',
    ],
    features: {
      'outer Material':
        'EVA + synthetic. Breathable and comfortable, thin like a skin.',
      'inner Material': 'Unlined',
      sole: 'Lightweight EVA sole, very light. Soft soles, comfortable and elastic.',
      closure: 'Buckle',
      'heel Height': '2 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Schmal',
    },
  },
  {
    id: 24,
    url: 'https://www.amazon.co.uk/dp/B08CF25Q1L',
    title: "Hugo Boss Men's Mirage_Tenn_oxcm Sneaker",
    price: 71.81,
    brand: 'Hugo Boss',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/3149rshrw9S.jpg',
      'https://m.media-amazon.com/images/I/41uaS4y1zeS.jpg',
      'https://m.media-amazon.com/images/I/41EXKeQ008S.jpg',
      'https://m.media-amazon.com/images/I/31XXN3ts+1S.jpg',
      'https://m.media-amazon.com/images/I/31EuCZsi5cS.jpg',
      'https://m.media-amazon.com/images/I/31dHdXQ6byS.jpg',
      'https://m.media-amazon.com/images/I/313lbdYXWOS.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Leather',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 25,
    url: 'https://www.amazon.co.uk/dp/B09B455S7B',
    title:
      'Absolute Footwear Mens Twin Gusset Slip On Velour Style Checked Winter Slippers',
    price: 77.85,
    brand: 'Visit the Absolute Footwear Store',
    categoryId: 24,
    images: [
      'https://m.media-amazon.com/images/I/41qDDJ5CiyL.jpg',
      'https://m.media-amazon.com/images/I/41i-y1kqwxL.jpg',
      'https://m.media-amazon.com/images/I/51LMFmK6qwL.jpg',
      'https://m.media-amazon.com/images/I/31CtMHLrvdL.jpg',
      'https://m.media-amazon.com/images/I/31drIW8SdWL.jpg',
      'https://m.media-amazon.com/images/I/31TU8aXKgvL.jpg',
      'https://m.media-amazon.com/images/I/41SR7apauBL.jpg',
    ],
    features: {
      sizs: 'UK 7 - 12',
      'outer Material': 'Textile',
      'inner Material': 'Textile',
      sole: 'Synthetic',
      closure: 'Pull On',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 26,
    url: 'https://www.amazon.co.uk/dp/B0919PVV9Z',
    title:
      "adidas Men's Ultraboost 5.0 DNA Running Shoe, core Black/core Black/FTWR White, 10 UK",
    price: 90.11,
    brand: 'Visit the adidas Store',
    categoryId: 18,
    images: [
      'https://m.media-amazon.com/images/I/41+wLQIk9uL.jpg',
      'https://m.media-amazon.com/images/I/41jKBzvlN8L.jpg',
      'https://m.media-amazon.com/images/I/41ucXx87HPL.jpg',
      'https://m.media-amazon.com/images/I/41SyRI6G6UL.jpg',
      'https://m.media-amazon.com/images/I/413qDSaUCzL.jpg',
      'https://m.media-amazon.com/images/I/41JCaLnmPKL.jpg',
      'https://m.media-amazon.com/images/I/41EL+iYn8PL.jpg',
    ],
    features: {
      'outer Material': 'Cotton',
      'inner Material': 'Canvas',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 27,
    url: 'https://www.amazon.co.uk/dp/B084DQPC13',
    title: "Clarks Men's Bayhill Plain Oxford",
    price: 28.84,
    brand: 'Visit the Clarks Store',
    categoryId: 25,
    images: [
      'https://m.media-amazon.com/images/I/31B4LeV-WbL.jpg',
      'https://m.media-amazon.com/images/I/412jkzCjB6L.jpg',
      'https://m.media-amazon.com/images/I/41-HU6rtq5L.jpg',
      'https://m.media-amazon.com/images/I/31wSdYxy+eL.jpg',
      'https://m.media-amazon.com/images/I/31qVaT2nYYL.jpg',
      'https://m.media-amazon.com/images/I/31fW4B5Hu7L.jpg',
      'https://m.media-amazon.com/images/I/31Wr27F2MAL.jpg',
    ],
    features: {
      'outer Material': 'Nubuck Leather',
      'inner Material': 'Manmade',
      sole: 'Leather and rubber',
      closure: 'Lace-Up',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Wide',
    },
  },
  {
    id: 28,
    url: 'https://www.amazon.co.uk/dp/B08898G4DM',
    title: "Kappa Unisex's Sneem Sneaker",
    price: 87.14,
    brand: 'Visit the Kappa Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/41eDCN36+GL.jpg',
      'https://m.media-amazon.com/images/I/41HQDFqs2YL.jpg',
      'https://m.media-amazon.com/images/I/41rxJIBfEHL.jpg',
      'https://m.media-amazon.com/images/I/31kqXfKlpnL.jpg',
      'https://m.media-amazon.com/images/I/311r1-Gy42L.jpg',
      'https://m.media-amazon.com/images/I/413YHAqTE5L.jpg',
      'https://m.media-amazon.com/images/I/41ONGE8vtBL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Pull On',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 29,
    url: 'https://www.amazon.co.uk/dp/B08RXW73XF',
    title: "Teva Unisex Kid's K Midform Universal Sandals",
    price: 52.0,
    brand: 'Visit the Teva Store',
    categoryId: 28,
    images: ['https://m.media-amazon.com/images/I/41U7yOvW4IS.jpg'],
    features: {
      'great for': 'all day wear, festivals, moving around town',
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Hook and loop',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 30,
    url: 'https://www.amazon.co.uk/dp/B00307JJR0',
    title: 'Capezio Websneaker, Girls’ Casual',
    price: 86.22,
    brand: 'Capezio',
    categoryId: 7,
    images: [
      'https://m.media-amazon.com/images/I/41Vt3Tj1QKL.jpg',
      'https://m.media-amazon.com/images/I/41riQrO0ohL.jpg',
      'https://m.media-amazon.com/images/I/41lrVmFhYJL.jpg',
      'https://m.media-amazon.com/images/I/31Ll2xhEXkL.jpg',
      'https://m.media-amazon.com/images/I/31ZPOr8r-iL.jpg',
      'https://m.media-amazon.com/images/I/31D2vzKr-bL.jpg',
      'https://m.media-amazon.com/images/I/51UJMw+OZmL.jpg',
    ],
    features: {
      'outer Material': 'Mesh',
      'inner Material': 'Manmade',
      sole: 'Polyurethane',
      closure: 'Lace-Up',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 31,
    url: 'https://www.amazon.co.uk/dp/B07TVF6ZBP',
    title: "Skechers Women's Ultra Groove Trainers",
    price: 62.41,
    brand: 'Visit the Skechers Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/4105lS5DErL.jpg',
      'https://m.media-amazon.com/images/I/41Ao60M9swL.jpg',
      'https://m.media-amazon.com/images/I/41vFoI9bGjL.jpg',
      'https://m.media-amazon.com/images/I/31D7xyC46rL.jpg',
      'https://m.media-amazon.com/images/I/31eewoLkYWL.jpg',
      'https://m.media-amazon.com/images/I/41+7Sbi3ylL.jpg',
      'https://m.media-amazon.com/images/I/41nXEm1EipL.jpg',
    ],
    features: {
      upper: 'Textile',
      lining: 'Textile',
      'outer Material': 'Synthetic',
      'inner Material': 'Textile',
      sole: 'EVA',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'Medium',
      'heel Height': '45',
      width: 'Standard',
    },
  },
  {
    id: 32,
    url: 'https://www.amazon.co.uk/dp/B07W6S18DB',
    title:
      'Rieker Women Low Shoes, Loafers L2327, Ladies Low-Tops,Removable Insole',
    price: 88.46,
    brand: 'Rieker',
    categoryId: 30,
    images: [
      'https://m.media-amazon.com/images/I/41IyKyn39IL.jpg',
      'https://m.media-amazon.com/images/I/41H0mKED6DL.jpg',
      'https://m.media-amazon.com/images/I/31EfSTJwvnL.jpg',
      'https://m.media-amazon.com/images/I/31do7yetmuL.jpg',
      'https://m.media-amazon.com/images/I/41aoDZ-yWLL.jpg',
      'https://m.media-amazon.com/images/I/41oKiyT8YKL.jpg',
      'https://m.media-amazon.com/images/I/4164t8o2+6L.jpg',
    ],
    features: {
      'product type':
        'Low shoes, Loafers,Low-tops,low shoe,street shoe,lace up,lace up shoe,sports shoe,platform sole,leisure',
      'outer material': 'textile',
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Height': '3.5 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
      'heel type': 'ankle',
      width: 'Lace-Up',
    },
  },
  {
    id: 33,
    url: 'https://www.amazon.co.uk/dp/B08Z7SY2R9',
    title:
      'Little/Big Boys Girls Lightweight Graffiti Personality Shoes Kids Sneaker Mesh Breathable Athletic Running Tennis Shoes(Size:30,Color:C)',
    price: 74.2,
    brand: 'QBSW',
    categoryId: 3,
    images: [
      'https://m.media-amazon.com/images/I/41te42GqtKL.jpg',
      'https://m.media-amazon.com/images/I/41gyUdNLHKL.jpg',
      'https://m.media-amazon.com/images/I/41jNrWW8oWL.jpg',
      'https://m.media-amazon.com/images/I/51XzjbHwHKL.jpg',
      'https://m.media-amazon.com/images/I/41usxHbeYYL.jpg',
      'https://m.media-amazon.com/images/I/41oBUAgN56L.jpg',
      'https://m.media-amazon.com/images/I/51-DXTWevdL.jpg',
    ],
    features: {
      occasions:
        'outdoor sports, vacation, school, church, travel, walking with dogs, daily wear, etc.',
    },
  },
  {
    id: 34,
    url: 'https://www.amazon.co.uk/dp/B07XJR94FR',
    title: "dockers Men's Sunland Slide Sandal",
    price: 67.47,
    brand: 'Visit the Dockers Store',
    categoryId: 31,
    images: [
      'https://m.media-amazon.com/images/I/31gygukQhsL.jpg',
      'https://m.media-amazon.com/images/I/51OWnyA2LYL.jpg',
      'https://m.media-amazon.com/images/I/41-3bmbJNML.jpg',
      'https://m.media-amazon.com/images/I/31j3yKl4jLL.jpg',
      'https://m.media-amazon.com/images/I/31xOoMGychL.jpg',
      'https://m.media-amazon.com/images/I/31HnRbldQBL.jpg',
      'https://m.media-amazon.com/images/I/31qWb4k630L.jpg',
    ],
    features: {
      'outer Material': 'Faux Leather',
      sole: 'Rubber',
      closure: 'Slip On',
      'heel Height': '1 inches',
      'heel Type': 'low-heel',
      'shoe Width': 'Medium mens_us',
    },
  },
  {
    id: 35,
    url: 'https://www.amazon.co.uk/dp/B071HXDK1Z',
    title:
      "Nine West Kids' Odettah Sneaker, Grey Jersey, Size 6 Medium US Big Kid US/US",
    price: 69.16,
    brand: 'NINE WEST',
    categoryId: 33,
    images: [
      'https://m.media-amazon.com/images/I/41QLa6nt5XL.jpg',
      'https://m.media-amazon.com/images/I/517ie0SQJQL.jpg',
      'https://m.media-amazon.com/images/I/511A98FLp3L.jpg',
      'https://m.media-amazon.com/images/I/41wGq3Q3btL.jpg',
      'https://m.media-amazon.com/images/I/411Enic5oOL.jpg',
      'https://m.media-amazon.com/images/I/31TnjpC-McL.jpg',
      'https://m.media-amazon.com/images/I/41GWAzVyCPL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Pull On',
      'shoe Width': 'M',
      style: 'Odettah',
      closure_type: 'Slip-On',
    },
  },
  {
    id: 36,
    url: 'https://www.amazon.co.uk/dp/B09C8C5T8K',
    title:
      'Walk Shoes Women Athletic Casual Tennis Sneakers Lace Up Walking Shoes Striped Pattern Autumn Loafers',
    price: 22.1,
    brand: 'JYC Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41+GJL894TS.jpg',
      'https://m.media-amazon.com/images/I/61p6xGBYBUS.jpg',
      'https://m.media-amazon.com/images/I/611-z94F6pS.jpg',
      'https://m.media-amazon.com/images/I/61R4I7CeCZS.jpg',
      'https://m.media-amazon.com/images/I/51CPIGt9ewS.jpg',
      'https://m.media-amazon.com/images/I/5186i6L8P9S.jpg',
      'https://m.media-amazon.com/images/I/41i3VF92QXL.jpg',
    ],
    features: {
      'outer Material':
        "Canvas, boys trainers, badminton shoes, women's walking shoes, running shoes for wome",
      'inner Material':
        "Wedge, pointed-toe, women's slippers, white trainers women",
      sole: 'Rubber',
      closure: 'Lace-Up, Pull On, Hook & Loop',
      'heel Height': '1.5 centimetres',
      'heel Type': 'Low',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 37,
    url: 'https://www.amazon.co.uk/dp/B07P23G5X9',
    title: "Skechers Men's Dyna-air - Blyce Trainers",
    price: 55.49,
    brand: 'Visit the Skechers Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/410vpTfvXNL.jpg',
      'https://m.media-amazon.com/images/I/51k5ljDwwjL.jpg',
      'https://m.media-amazon.com/images/I/41vwxRibYAL.jpg',
      'https://m.media-amazon.com/images/I/41UmwaMM9kL.jpg',
      'https://m.media-amazon.com/images/I/41U2h9zA22L.jpg',
      'https://m.media-amazon.com/images/I/41BxWTUBPsL.jpg',
      'https://m.media-amazon.com/images/I/41VH-yA01rL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Textile',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium mens_us',
    },
  },
  {
    id: 38,
    url: 'https://www.amazon.co.uk/dp/B07DW6XC32',
    title: 'Puma - Infant Suede Classic Bboy Fabulous Shoes',
    price: 91.1,
    brand: 'Visit the PUMA Store',
    categoryId: 36,
    images: [
      'https://m.media-amazon.com/images/I/41ZdwZEHJCL.jpg',
      'https://m.media-amazon.com/images/I/41nCRg7k83L.jpg',
      'https://m.media-amazon.com/images/I/41rnV1x1baL.jpg',
      'https://m.media-amazon.com/images/I/41u3LHhDxwL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 39,
    url: 'https://www.amazon.co.uk/dp/B08J7ZXK8C',
    title: "IGI&Co Men's Urt 71131 Oxford",
    price: 93.82,
    brand: 'IGI&Co',
    categoryId: 25,
    images: [
      'https://m.media-amazon.com/images/I/41TJYpNDhcL.jpg',
      'https://m.media-amazon.com/images/I/41fHDa7rR4L.jpg',
      'https://m.media-amazon.com/images/I/41SM1QErOXL.jpg',
      'https://m.media-amazon.com/images/I/31voIphEKbL.jpg',
      'https://m.media-amazon.com/images/I/313CoZWNmwL.jpg',
      'https://m.media-amazon.com/images/I/31MwvY5mpeL.jpg',
      'https://m.media-amazon.com/images/I/41djag9UkIL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Height': '0.5 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Normale',
    },
  },
  {
    id: 40,
    url: 'https://www.amazon.co.uk/dp/B0743BKHVW',
    title:
      "Jamron Men's Suede Leather Penny Loafers Comfort Driving Shoes Moccasin Slippers",
    price: 63.89,
    brand: 'Visit the Jamron Store',
    categoryId: 11,
    images: [
      'https://m.media-amazon.com/images/I/51MkgEHu8tL.jpg',
      'https://m.media-amazon.com/images/I/41EppO8jKFL.jpg',
      'https://m.media-amazon.com/images/I/41gVQ6qrlbL.jpg',
      'https://m.media-amazon.com/images/I/61vMSwkRDyL.jpg',
      'https://m.media-amazon.com/images/I/51a6ps5JDSL.jpg',
      'https://m.media-amazon.com/images/I/51KAhdGMCQL.jpg',
      'https://m.media-amazon.com/images/I/516UbQuxp+L.jpg',
    ],
    features: {
      'outer Material': 'Suede Leather',
      'inner Material': 'Leather',
      sole: 'Rubber',
      closure: 'Pull On',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Normal',
    },
  },
  {
    id: 41,
    url: 'https://www.amazon.co.uk/dp/B00AYXO92S',
    title:
      'Pure and Precious White Satin Bridesmaids Bridal Flower Girls Communion Childrens Shoes 7,8,9,10,11,12,13,1,2,3 Isabella L/H',
    price: 66.76,
    brand: 'Pure and Precious',
    categoryId: 37,
    images: ['https://m.media-amazon.com/images/I/317BTxvkJsL.jpg'],
    features: {
      'outer Material': 'Satin',
      closure: 'Buckle',
      'heel Height': '3 centimetres',
      'material Composition': '100 % satin',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 42,
    url: 'https://www.amazon.co.uk/dp/B08PKY8MPQ',
    title: "Geox Girl's J Calco Shoes",
    price: 81.78,
    brand: 'Visit the Geox Store',
    categoryId: 33,
    images: [
      'https://m.media-amazon.com/images/I/41bCZtu2QtL.jpg',
      'https://m.media-amazon.com/images/I/416MtIeNekL.jpg',
      'https://m.media-amazon.com/images/I/41L0tfH-5xL.jpg',
      'https://m.media-amazon.com/images/I/31FnZt5j5CL.jpg',
      'https://m.media-amazon.com/images/I/41IKJgbyr4L.jpg',
      'https://m.media-amazon.com/images/I/41vIEnVEEVL.jpg',
      'https://m.media-amazon.com/images/I/31dpyha3MdL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Canvas',
      sole: 'Rubber',
      closure: 'Hook & Loop',
      'heel Type': 'Flat',
      'shoe Width': 'Normal',
    },
  },
  {
    id: 43,
    url: 'https://www.amazon.co.uk/dp/B08VWZB2XC',
    title: "Primigi Pwt 84295, Girl's Mary Jane",
    price: 101.56,
    brand: 'Primigi',
    categoryId: 38,
    images: [
      'https://m.media-amazon.com/images/I/41wOh27Y32L.jpg',
      'https://m.media-amazon.com/images/I/41eiFExd1IL.jpg',
      'https://m.media-amazon.com/images/I/41RNH04YvIL.jpg',
      'https://m.media-amazon.com/images/I/31Ro3K4IQjL.jpg',
      'https://m.media-amazon.com/images/I/31M757KWudL.jpg',
      'https://m.media-amazon.com/images/I/31t8t-LrvSL.jpg',
      'https://m.media-amazon.com/images/I/41fuQj7wBCL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Leather',
      sole: 'Rubber',
      closure: 'Hook & Loop',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 44,
    url: 'https://www.amazon.co.uk/dp/B0851FNQ55',
    title: "Finn Comfort Sidonia Women's Low Shoes",
    price: 52.21,
    brand: 'FinnComfort',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41jIK82gtEL.jpg',
      'https://m.media-amazon.com/images/I/41jOLn7taqL.jpg',
      'https://m.media-amazon.com/images/I/41FK2YYq51L.jpg',
      'https://m.media-amazon.com/images/I/41ablzDu9KL.jpg',
    ],
    features: {
      colour: 'black',
      material: 'nubuck leather',
      'outer Material': 'Leather',
      'inner Material': 'Vegetable-tanned leather',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Height': '18 millimetres',
      'shoe Width': 'Schmal',
      style: 'lace-up shoes',
      shape: 'City-Sport',
      'detail colour': 'black (902132)',
    },
  },
  {
    id: 45,
    url: 'https://www.amazon.co.uk/dp/B0855JYDSV',
    title: "Reebok Women's Lite 2.0 Running Shoe",
    price: 82.34,
    brand: 'Visit the Reebok Store',
    categoryId: 39,
    images: [
      'https://m.media-amazon.com/images/I/310why27JWL.jpg',
      'https://m.media-amazon.com/images/I/41rOLoaVN7L.jpg',
      'https://m.media-amazon.com/images/I/41EGvw-5riL.jpg',
      'https://m.media-amazon.com/images/I/213OZWHVtHL.jpg',
      'https://m.media-amazon.com/images/I/31n-IvpFDeL.jpg',
      'https://m.media-amazon.com/images/I/31lRnIliRvL.jpg',
      'https://m.media-amazon.com/images/I/31yf4ag7-ZL.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'low-heel',
      'shoe Width': 'M',
    },
  },
  {
    id: 46,
    url: 'https://www.amazon.co.uk/dp/B0895HSVJB',
    title:
      "Women's running shoes hiking for women leisure slip fashion sports outdoor shoes.",
    price: 32.24,
    brand: 'Lingmu',
    categoryId: 7,
    images: [
      'https://m.media-amazon.com/images/I/51N8kZPRQmL.jpg',
      'https://m.media-amazon.com/images/I/51CmCtwEZmL.jpg',
      'https://m.media-amazon.com/images/I/41YWTVdl5oL.jpg',
      'https://m.media-amazon.com/images/I/41zx2eWXqxL.jpg',
      'https://m.media-amazon.com/images/I/416pHrfJhUL.jpg',
      'https://m.media-amazon.com/images/I/51GyLNX-5jL.jpg',
      'https://m.media-amazon.com/images/I/51AWMtDaFdL.jpg',
    ],
    features: {
      'fashionable knitted mesh upper':
        'ultra-light support and breathability maximise the upper material and keep your feet dry and cool all the time',
      'inner honeycomb design':
        'keep your feet balanced, dampen shocks and maximise ventilation',
      'outer Material': 'Rubber',
      closure: 'Lace-Up',
      'heel Height': '3 centimetres',
      'shoe Width': 'Normal',
      'sports shoes':
        'The sole is made of hollow carved technology to provide stable support and best shock absorption for sports',
      'fashionable hollow sole':
        'clear texture of the outsole, non-slip grip, excellent elasticity.',
    },
  },
  {
    id: 47,
    url: 'https://www.amazon.co.uk/dp/B0815SFX5J',
    title: 'TOMS Berkeley Slippers',
    price: 106.76,
    brand: 'Visit the TOMS Store',
    categoryId: 24,
    images: [
      'https://m.media-amazon.com/images/I/31TgFwmpYwL.jpg',
      'https://m.media-amazon.com/images/I/31EO1OhTGZL.jpg',
      'https://m.media-amazon.com/images/I/41uI58x+5KL.jpg',
      'https://m.media-amazon.com/images/I/41KTsJzGrIL.jpg',
      'https://m.media-amazon.com/images/I/41HBMFx1YTL.jpg',
      'https://m.media-amazon.com/images/I/31BrbGXyIjL.jpg',
      'https://m.media-amazon.com/images/I/31KyZWAfpXL.jpg',
    ],
    features: {
      'outer Material': 'Textile',
      'inner Material': 'Faux Shearling',
      sole: 'Rubber',
      closure: 'Pull On',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 48,
    url: 'https://www.amazon.co.uk/dp/B078SXZKGW',
    title: "Mammut Women's Alnasca Knit Low Rise Hiking Boots",
    price: 29.29,
    brand: 'Mammut',
    categoryId: 23,
    images: [
      'https://m.media-amazon.com/images/I/41IyEpbhPHL.jpg',
      'https://m.media-amazon.com/images/I/51lT7Cu6TtL.jpg',
      'https://m.media-amazon.com/images/I/41yssBEZqWL.jpg',
      'https://m.media-amazon.com/images/I/31ot1rnSkBL.jpg',
      'https://m.media-amazon.com/images/I/41F-k4AGtTL.jpg',
      'https://m.media-amazon.com/images/I/41fvWtU8oSL.jpg',
      'https://m.media-amazon.com/images/I/51DJstRydEL.jpg',
    ],
    features: {
      'specific activity': 'Via Ferrata, Hiking',
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'material Composition':
        'Rubber, EVA, Misc. material (Shoe sole material) Polyester, Polyurethane, Natural and synthetic textiles (Outer shoe material) Polyester, Natural and synthetic textiles (Shoe lining material)',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 49,
    url: 'https://www.amazon.co.uk/dp/B08Q4DR8PW',
    title: "Clarks Women's Layton Step Sneaker",
    price: 88.65,
    brand: 'Visit the Clarks Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31L30W7UhCL.jpg',
      'https://m.media-amazon.com/images/I/31o7ieHkMGL.jpg',
      'https://m.media-amazon.com/images/I/41M2Fevs0AL.jpg',
      'https://m.media-amazon.com/images/I/11iGBJSePGL.jpg',
      'https://m.media-amazon.com/images/I/31y1FTry2pL.jpg',
      'https://m.media-amazon.com/images/I/31AIuTQt7OL.jpg',
      'https://m.media-amazon.com/images/I/31OTppaUDPL.jpg',
    ],
    features: {
      'outer Material': 'Smooth Leather',
      'inner Material': 'Manmade',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Zip',
      'heel Height': '2 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 50,
    url: 'https://www.amazon.co.uk/dp/B08316WSF6',
    title:
      'JIASUQI Water Shoes Mens Womens Quick Dry Sports Aqua Shoes Unisex Swim Beach Driving Boating Shoes',
    price: 25.51,
    brand: 'Visit the JIASUQI Store',
    categoryId: 40,
    images: [
      'https://m.media-amazon.com/images/I/41YeVmP9LoL.jpg',
      'https://m.media-amazon.com/images/I/41sHKnIJWKL.jpg',
      'https://m.media-amazon.com/images/I/41K6LgsJRsL.jpg',
      'https://m.media-amazon.com/images/I/41GnxITzpmL.jpg',
      'https://m.media-amazon.com/images/I/41mDkipPr9L.jpg',
      'https://m.media-amazon.com/images/I/41DxxdhLV-L.jpg',
      'https://m.media-amazon.com/images/I/41pdHpE342L.jpg',
    ],
    features: {
      'noN-SLIP': 'Lightest slip resistant cushion sole.',
      'perfect MATERIAL':
        'Upper with stretch breathable ultra light weight fabric for fast draining and cross ventilation, give you excellent flexible and comfortable. Quick-drying materials.',
      'outer Material': 'Polyester',
      'inner Material': 'Mesh',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
      'elastic STRAPS':
        'According to the width of the foot quickly adjust the shoes elastic and avoid the annoyance of tying your shoes.',
      'elastic and Breathable':
        'Water shoes upper with stretch breathable ultra light weight fabric lycra for fast draining and cross ventilation, enjoy a barefoot feeling no matter what activity you do.',
      occasions:
        'Perfect for beach, swimming, surf, pool, sailing, boating, kayaking, windsurfing, beach volleyball etc.',
    },
  },
  {
    id: 51,
    url: 'https://www.amazon.co.uk/dp/B0824HNXX5',
    title: "MARCO TOZZI Women's 2-2-23754-35 Sneaker",
    price: 24.74,
    brand: 'Marco Tozzi',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41g4MQxA8AL.jpg',
      'https://m.media-amazon.com/images/I/41RP1eJKcqL.jpg',
      'https://m.media-amazon.com/images/I/41vqn9xsEML.jpg',
      'https://m.media-amazon.com/images/I/41Dg8q6URqL.jpg',
      'https://m.media-amazon.com/images/I/31we6giAQ-L.jpg',
    ],
    features: {
      'outer Material': 'Material mix made from leather and textile',
      'inner Material': 'Material mix of textile and synthetic',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Height': '4 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 52,
    url: 'https://www.amazon.co.uk/dp/B08411RBM3',
    title: "PUMA Men's El Rey 2 Perf Sneaker",
    price: 25.95,
    brand: 'Visit the PUMA Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/31nDRF+18zL.jpg',
      'https://m.media-amazon.com/images/I/41fDWigjB7L.jpg',
      'https://m.media-amazon.com/images/I/412bxYVtsXL.jpg',
      'https://m.media-amazon.com/images/I/31tKdSWjROL.jpg',
      'https://m.media-amazon.com/images/I/31353Xlws6L.jpg',
      'https://m.media-amazon.com/images/I/31IceqeyO9L.jpg',
      'https://m.media-amazon.com/images/I/31lHSWRw6dL.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 53,
    url: 'https://www.amazon.co.uk/dp/B01ENA48S2',
    title: 'T.U.K. Shoes Burgundy Rub-Off Monk Buckle Pointed Creepers 3 UK',
    price: 95.75,
    brand: 'T.U.K. Shoes',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/41NTacc4AgL.jpg',
      'https://m.media-amazon.com/images/I/41d1WEhR6sL.jpg',
      'https://m.media-amazon.com/images/I/41YSGeMUsdL.jpg',
      'https://m.media-amazon.com/images/I/41AzeeUhO3L.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Textile',
      sole: 'Rubber',
      closure: 'Buckle',
      'heel Height': '2 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Normale',
    },
  },
  {
    id: 54,
    url: 'https://www.amazon.co.uk/dp/B08868TDGH',
    title: "Skechers womens 155090 Skecher Street Women's Uno - Sky Pop Size:",
    price: 29.99,
    brand: 'Visit the Skechers Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41LUtoTh2VL.jpg',
      'https://m.media-amazon.com/images/I/41LoB7MxIoL.jpg',
      'https://m.media-amazon.com/images/I/31-3I9AK5WL.jpg',
      'https://m.media-amazon.com/images/I/313hiJXJBEL.jpg',
      'https://m.media-amazon.com/images/I/31v92vL79nL.jpg',
      'https://m.media-amazon.com/images/I/41RDqH5MAFL.jpg',
      'https://m.media-amazon.com/images/I/412GkKHVIBL.jpg',
    ],
    features: {
      upper: 'Synthetic / textile',
      'outer Material': 'Suede',
      'inner Material': 'Suede',
      sole: 'Suede',
      closure: 'Lace-Up',
      'heel Height': '1 centimetres',
      'heel Type': 'Platform',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 55,
    url: 'https://www.amazon.co.uk/dp/B08N6Y3BKD',
    title: "adidas Unisex Kid's Duramo Sl Running Shoe",
    price: 101.84,
    brand: 'Visit the adidas Store',
    categoryId: 42,
    images: [
      'https://m.media-amazon.com/images/I/31ncM3oyYES.jpg',
      'https://m.media-amazon.com/images/I/41yILGMN-hS.jpg',
      'https://m.media-amazon.com/images/I/31CoYUbqq4S.jpg',
      'https://m.media-amazon.com/images/I/3105KobCIiS.jpg',
      'https://m.media-amazon.com/images/I/31Wx+QyjDOS.jpg',
      'https://m.media-amazon.com/images/I/31v9WCSx0rS.jpg',
      'https://m.media-amazon.com/images/I/31cwYq1R+uS.jpg',
    ],
    features: {
      'outer Material': 'fabric',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'medium',
    },
  },
  {
    id: 56,
    url: 'https://www.amazon.co.uk/dp/B00SBEOH9C',
    title: "NINE WEST Women's Bachney Fabric Fashion Sneaker",
    price: 31.44,
    brand: 'NINE WEST',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41pgaDf9N6L.jpg',
      'https://m.media-amazon.com/images/I/41M1Nwzt67L.jpg',
      'https://m.media-amazon.com/images/I/411TziiloEL.jpg',
      'https://m.media-amazon.com/images/I/31eExz2l99L.jpg',
      'https://m.media-amazon.com/images/I/41tl9THORpL.jpg',
      'https://m.media-amazon.com/images/I/41JqApbVCQL.jpg',
      'https://m.media-amazon.com/images/I/411g6JlTg2L.jpg',
    ],
    features: {
      sole: 'Synthetic',
      closure: 'Zipper and Lace-up',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 57,
    url: 'https://www.amazon.co.uk/dp/B07F3YBJJC',
    title: "Legero Women's Tanaro Trainer",
    price: 116.83,
    brand: 'Legero',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31WTUI615GL.jpg',
      'https://m.media-amazon.com/images/I/31BPferGiiL.jpg',
      'https://m.media-amazon.com/images/I/41jYV+fyl3L.jpg',
      'https://m.media-amazon.com/images/I/317EUxDO6tL.jpg',
      'https://m.media-amazon.com/images/I/31GlOrUF01L.jpg',
      'https://m.media-amazon.com/images/I/31Ptox+WC5L.jpg',
      'https://m.media-amazon.com/images/I/31123jUVrqL.jpg',
    ],
    features: {
      'outer Material': 'NAPPALEDER',
      'inner Material': 'Textile lining',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Height': '2 centimetres',
      'heel Type': 'Flat',
      'material Composition': 'Textile, softly padded',
      'fit Type': 'Comfortable fit',
      'shoe Width': 'Normal',
      fastening: 'not specified',
    },
  },
  {
    id: 58,
    url: 'https://www.amazon.co.uk/dp/B082Q35XK3',
    title: 'Altra Escalante 2.5 Running Shoes - SS21',
    price: 56.38,
    brand: 'Altra',
    categoryId: 18,
    images: [
      'https://m.media-amazon.com/images/I/41BUbcUEb0L.jpg',
      'https://m.media-amazon.com/images/I/41PPch62iuL.jpg',
      'https://m.media-amazon.com/images/I/41QZ-MVlNXL.jpg',
      'https://m.media-amazon.com/images/I/41IIJlLSZFL.jpg',
      'https://m.media-amazon.com/images/I/31u7rY8bD6L.jpg',
      'https://m.media-amazon.com/images/I/31UV6zC3WFL.jpg',
      'https://m.media-amazon.com/images/I/31Tk-+1TKQL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Lace-Up',
      'material Composition': 'Synthetic',
      'shoe Width': 'D',
    },
  },
  {
    id: 59,
    url: 'https://www.amazon.co.uk/dp/B07DG317MX',
    title: 'Regatta Boys Westshore Jnr Closed Toe Sandals',
    price: 100.55,
    brand: 'Visit the Regatta Store',
    categoryId: 3,
    images: [
      'https://m.media-amazon.com/images/I/41rag1pFhkL.jpg',
      'https://m.media-amazon.com/images/I/41m16ZT5WhL.jpg',
      'https://m.media-amazon.com/images/I/41Zwguo-uEL.jpg',
      'https://m.media-amazon.com/images/I/41oYY9bWu1L.jpg',
      'https://m.media-amazon.com/images/I/41u1Y9YsIxL.jpg',
      'https://m.media-amazon.com/images/I/41fil2xWJFL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      sole: 'Synthetic Rubber',
      closure: 'Hook & Loop',
    },
  },
  {
    id: 60,
    url: 'https://www.amazon.co.uk/dp/B08H8MBBRC',
    title: "Kappa Unisex's Feeny Sneaker",
    price: 77.53,
    brand: 'Visit the Kappa Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/314QhnsFbUL.jpg',
      'https://m.media-amazon.com/images/I/31xzystgdtL.jpg',
      'https://m.media-amazon.com/images/I/41SiOyrmUEL.jpg',
      'https://m.media-amazon.com/images/I/41fwu865R9L.jpg',
      'https://m.media-amazon.com/images/I/41RIX7mS6dL.jpg',
      'https://m.media-amazon.com/images/I/31pUG5bJtlL.jpg',
      'https://m.media-amazon.com/images/I/312XtC3VlyL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 61,
    url: 'https://www.amazon.co.uk/dp/B07Q4JL2VS',
    title: "adidas Women's Advantage Sneaker",
    price: 51.93,
    brand: 'Visit the adidas Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31vkZrc0j-L.jpg',
      'https://m.media-amazon.com/images/I/31r9fgkoSfL.jpg',
      'https://m.media-amazon.com/images/I/313+4pIh8FL.jpg',
      'https://m.media-amazon.com/images/I/21EgiyfAQAL.jpg',
      'https://m.media-amazon.com/images/I/310D9s5WObL.jpg',
      'https://m.media-amazon.com/images/I/31VCHZ0XAlL.jpg',
      'https://m.media-amazon.com/images/I/31YwAmLxdeL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 62,
    url: 'https://www.amazon.co.uk/dp/B074QT3LBW',
    title: "FRYE Women's Lily Leather Ring Slide Sneaker",
    price: 63.08,
    brand: 'FRYE',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31qtKem0v0L.jpg',
      'https://m.media-amazon.com/images/I/41litMqCbFL.jpg',
      'https://m.media-amazon.com/images/I/41lMPmSpYQL.jpg',
      'https://m.media-amazon.com/images/I/31IXwHcl04L.jpg',
      'https://m.media-amazon.com/images/I/31aBnv1kEjL.jpg',
      'https://m.media-amazon.com/images/I/31xfbE2mDZL.jpg',
      'https://m.media-amazon.com/images/I/41EchOIVwFL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      sole: 'Rubber',
      closure: 'Pull On',
      'heel Height': '1 inches',
      'heel Type': 'No Heel',
      'shoe Width': 'M',
    },
  },
  {
    id: 63,
    url: 'https://www.amazon.co.uk/dp/B00RBZ6TR0',
    title: 'Champion Cotton Tee Mens',
    price: 60.95,
    brand: 'Visit the Champion Store',
    categoryId: 10,
    images: [
      'https://m.media-amazon.com/images/I/419l-f9lxUL.jpg',
      'https://m.media-amazon.com/images/I/419l-f9lxUL.jpg',
      'https://m.media-amazon.com/images/I/418fSuFnaTL.jpg',
    ],
    features: {
      'shoe Width': 'D(M) mens_us',
    },
  },
  {
    id: 64,
    url: 'https://www.amazon.co.uk/dp/B07S5QWS59',
    title: "adidas Originals Women's Modern 80 EUR Court W Crib Shoe",
    price: 78.36,
    brand: 'adidas Originals',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/31hg-1VJOEL.jpg',
      'https://m.media-amazon.com/images/I/41trZBKlg-L.jpg',
      'https://m.media-amazon.com/images/I/41x5x9VRcjL.jpg',
      'https://m.media-amazon.com/images/I/31Y4vBFQEVL.jpg',
      'https://m.media-amazon.com/images/I/31bbkkq8q2L.jpg',
      'https://m.media-amazon.com/images/I/314dLZ9n+JL.jpg',
      'https://m.media-amazon.com/images/I/315XoPoz9CL.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 65,
    url: 'https://www.amazon.co.uk/dp/B07LFVV6R2',
    title: 'Geox J Snake.2 Boy a Low-Top Sneakers',
    price: 113.81,
    brand: 'Visit the Geox Store',
    categoryId: 43,
    images: [
      'https://m.media-amazon.com/images/I/31nhErfcm6L.jpg',
      'https://m.media-amazon.com/images/I/41-DZ4+SQ7L.jpg',
      'https://m.media-amazon.com/images/I/41vaJEkS4pL.jpg',
      'https://m.media-amazon.com/images/I/31+BTdrVslL.jpg',
      'https://m.media-amazon.com/images/I/31B0qUWs3fL.jpg',
      'https://m.media-amazon.com/images/I/314+Fg4ZkPL.jpg',
      'https://m.media-amazon.com/images/I/41sbRiIGIaL.jpg',
    ],
    features: {
      'outer Material': 'Smooth Leather',
      'inner Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Strap + Elastic Lace',
      'heel Height': '3 centimetres',
      'heel Type': 'Flat',
      'fit Type': 'Geox shoes have a comfortable fit',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 66,
    url: 'https://www.amazon.co.uk/dp/B09CGXPRSZ',
    title:
      'Boot Slippers Womens,Children\'S Slippers, Boys And Girls Cute Indoor Parent-Child Small Princess Anti-Skid, Wear Beach Bathroom Sandals Slippers-Long (205mm / 8.1"))_yellow',
    price: 78.17,
    brand: 'Perferct',
    categoryId: 44,
    images: [
      'https://m.media-amazon.com/images/I/417UppeLsVL.jpg',
      'https://m.media-amazon.com/images/I/418r613HM4L.jpg',
      'https://m.media-amazon.com/images/I/41LB8WyiGsL.jpg',
      'https://m.media-amazon.com/images/I/41SuPubVA8L.jpg',
      'https://m.media-amazon.com/images/I/41hHzA+D29L.jpg',
      'https://m.media-amazon.com/images/I/41-Qlno9x+L.jpg',
    ],
    features: {
      'ecO-FRIENDLY EVA MATERIAL':
        'Toddler summer slippers adopt environmentally friendly EVA material which is lightweight and flexible, durable non-slip outsole ensures toddlers wear more safety and let mom feel more at ease.',
    },
  },
  {
    id: 67,
    url: 'https://www.amazon.co.uk/dp/B07VPWG6ZD',
    title: "victoria Unisex's Arista Nylon Multicolor Trainers",
    price: 44.69,
    brand: 'VICTORIA',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/41ic4rSBA4L.jpg',
      'https://m.media-amazon.com/images/I/417xgJilTGL.jpg',
      'https://m.media-amazon.com/images/I/41vWpOi9KxL.jpg',
      'https://m.media-amazon.com/images/I/318m-U4djHL.jpg',
      'https://m.media-amazon.com/images/I/41MMp3LesmL.jpg',
      'https://m.media-amazon.com/images/I/41nYQFaQ49L.jpg',
      'https://m.media-amazon.com/images/I/41Tsgj3LPaL.jpg',
    ],
    features: {
      'outer Material': 'Fabric',
      'inner Material': 'Textile',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 68,
    url: 'https://www.amazon.co.uk/dp/B01GIJS710',
    title: 'Saucony Hurricane Iso 3 Running Shoes',
    price: 107.05,
    brand: 'Saucony',
    categoryId: 18,
    images: [
      'https://m.media-amazon.com/images/I/51GvyyP5UIL.jpg',
      'https://m.media-amazon.com/images/I/51pNGt+Lh4L.jpg',
      'https://m.media-amazon.com/images/I/517JDyoJLgL.jpg',
      'https://m.media-amazon.com/images/I/411qUCrtk1L.jpg',
      'https://m.media-amazon.com/images/I/41lExQ8NiGL.jpg',
      'https://m.media-amazon.com/images/I/41DYE0h2g1L.jpg',
      'https://m.media-amazon.com/images/I/51m8VNRgM9L.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'material Composition': 'Synthetic',
      'shoe Width': 'D',
    },
  },
  {
    id: 69,
    url: 'https://www.amazon.co.uk/dp/B00A1TMTY0',
    title:
      'Dikamar Administrator Wellington/Mens Boots/Plain Rubber Wellingtons',
    price: 59.68,
    brand: 'Visit the Dikamar Store',
    categoryId: -1,
    images: [],
    features: {},
  },
  {
    id: 70,
    url: 'https://www.amazon.co.uk/dp/B086TFKFL5',
    title: 'Falcotto Unisex Chimp Mid Calf Boot, Navy, 6 UK',
    price: 27.38,
    brand: 'Falcotto',
    categoryId: 45,
    images: [
      'https://m.media-amazon.com/images/I/41z7iRyKrqL.jpg',
      'https://m.media-amazon.com/images/I/41+IrV8968L.jpg',
      'https://m.media-amazon.com/images/I/31PesFL+nLL.jpg',
      'https://m.media-amazon.com/images/I/31T8lewfcaL.jpg',
      'https://m.media-amazon.com/images/I/31vC8HkJtdL.jpg',
      'https://m.media-amazon.com/images/I/31D2TeBThZL.jpg',
      'https://m.media-amazon.com/images/I/41C+3hK2XQL.jpg',
    ],
    features: {
      'outer Material': 'Other Leather',
      'inner Material': 'Wool',
      sole: 'Synthetic Rubber',
      closure: 'Hook & Loop',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 71,
    url: 'https://www.amazon.co.uk/dp/B088RH33PL',
    title: 'PUMA Unisex Adults X-RAY 2 Square Sneaker',
    price: 56.86,
    brand: 'Visit the PUMA Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/41ke+QBw+mL.jpg',
      'https://m.media-amazon.com/images/I/41bWF9NUg4L.jpg',
      'https://m.media-amazon.com/images/I/41zbyFv7SvL.jpg',
      'https://m.media-amazon.com/images/I/31U2awZCngL.jpg',
      'https://m.media-amazon.com/images/I/31T8LK9SDtL.jpg',
      'https://m.media-amazon.com/images/I/41iNCd2jy9L.jpg',
      'https://m.media-amazon.com/images/I/41--+lzf0XL.jpg',
    ],
    features: {
      activityGroup: 'Basics',
      ageGroup: 'Adults',
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'Medium',
      articleType: 'Low Boot',
      businessUnit: 'Athletic / Sport Leisure',
      midSole: 'IMEVA',
    },
  },
  {
    id: 72,
    url: 'https://www.amazon.co.uk/dp/B07DLHQNCY',
    title: 'Bisgaard Unisex Kids 70261.119 Ankle Strap Sandals',
    price: 104.51,
    brand: 'Bisgaard',
    categoryId: 20,
    images: [
      'https://m.media-amazon.com/images/I/41u62IWIaiL.jpg',
      'https://m.media-amazon.com/images/I/41gtBFdPVRL.jpg',
      'https://m.media-amazon.com/images/I/519jFXdxbUL.jpg',
      'https://m.media-amazon.com/images/I/41iCdgR+O4L.jpg',
      'https://m.media-amazon.com/images/I/41-rOfbDGAL.jpg',
      'https://m.media-amazon.com/images/I/315EsSRxF5L.jpg',
      'https://m.media-amazon.com/images/I/41lA-N4SlnL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Leather',
      sole: 'Rubber',
      closure: 'Buckle',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 73,
    url: 'https://www.amazon.co.uk/dp/B07Z7D63SG',
    title: 'Dublin Venturer Boots Iii',
    price: 95.66,
    brand: 'Dublin',
    categoryId: 47,
    images: [
      'https://m.media-amazon.com/images/I/21cW5x7nNeL.jpg',
      'https://m.media-amazon.com/images/I/41zzUrJt0kL.jpg',
      'https://m.media-amazon.com/images/I/51XMZVTHniL.jpg',
      'https://m.media-amazon.com/images/I/21cW5x7nNeL.jpg',
      'https://m.media-amazon.com/images/I/31miP6gZf6L.jpg',
      'https://m.media-amazon.com/images/I/41OWsnlQhhL.jpg',
    ],
    features: {
      closure: 'Slip-On',
    },
  },
  {
    id: 74,
    url: 'https://www.amazon.co.uk/dp/B07FK81RTV',
    title: "Tamaris Women's 1-1-23700-32 Low-Top Sneakers",
    price: 115.96,
    brand: 'Visit the Tamaris Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/315It9Kt81L.jpg',
      'https://m.media-amazon.com/images/I/41ApPSJ83TL.jpg',
      'https://m.media-amazon.com/images/I/411XOUalMiL.jpg',
      'https://m.media-amazon.com/images/I/21zbvaLUY0L.jpg',
      'https://m.media-amazon.com/images/I/313GOWCSA3L.jpg',
      'https://m.media-amazon.com/images/I/31+C9prvNCL.jpg',
      'https://m.media-amazon.com/images/I/31gQDDeVfbL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Textile',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 75,
    url: 'https://www.amazon.co.uk/dp/B096VWKH6T',
    title:
      'YQSHOES Women and Men Sock Sneakers Running Lightweight Breathable Casual Sports Shoes Fashion Sneakers Walking Shoes,Orange,39EU/7UK/7.5US',
    price: 49.15,
    brand: 'YQSHOES',
    categoryId: 48,
    images: [
      'https://m.media-amazon.com/images/I/512QtxOqitS.jpg',
      'https://m.media-amazon.com/images/I/51-TI5XgwgS.jpg',
      'https://m.media-amazon.com/images/I/51wcw4F-JFS.jpg',
      'https://m.media-amazon.com/images/I/51EYjPZFG4S.jpg',
      'https://m.media-amazon.com/images/I/51z5wzJMEwS.jpg',
      'https://m.media-amazon.com/images/I/614xoJdcBIS.jpg',
      'https://m.media-amazon.com/images/I/51WdL5gzijS.jpg',
    ],
    features: {
      Lightweight:
        'This knit stretch sock shoes uses breathable and lightweight Knit upper material allows your feet to breathe and ensures the lightweight feature.',
      'Breathable and dry':
        'This sock sneakers, Stretch breathable upper expand with your foot when you run and they more comfortable closely fit to help you reduce irritation. Ventilating shoes insole which thick to keep a dry, healthy and comfort foot environment.',
      'Applicable occasions':
        'These walking shoes are suitable for parties, daily walking, leisure, nursing, shopping, traveling, long-term standing, outdoor sports, driving, indoor, casual fashion and other occasions.',
      'Reinforced heel':
        'The heel is wrapped to provide sufficient support, comfortable cushioning, stable overall, and continuous protection.',
    },
  },
  {
    id: 76,
    url: 'https://www.amazon.co.uk/dp/B07BQYHJC7',
    title: "New Balance Men's 009 V1 Sneaker",
    price: 28.56,
    brand: 'Visit the New Balance Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/41A+XOQ43XL.jpg',
      'https://m.media-amazon.com/images/I/51wZk-QmJJL.jpg',
      'https://m.media-amazon.com/images/I/41bSq9WnjPL.jpg',
      'https://m.media-amazon.com/images/I/31z9IG2KWGL.jpg',
      'https://m.media-amazon.com/images/I/41tKXCUW3wL.jpg',
      'https://m.media-amazon.com/images/I/41sQbJLYQ7L.jpg',
      'https://m.media-amazon.com/images/I/41a-eC5kHkL.jpg',
    ],
    features: {
      "inspired by the '90s":
        "the New Balance 009 lifestyle shoe is a classic sneaker with design elements pulled straight out of the '90s. Often considered by sneaker heads as the golden era, 1990s inspiration offers clean, classic looks",
      'energizing technology':
        'taking style to the next level, These casual shoes feature impressive CUSH+ technology, delivering ultra-soft, all-day comfort. Ground Contact EVA takes comfort even further without adding weight or sacrificing support',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'material Composition': 'Synthetic/ Textile',
      'shoe Width': 'Medium',
      'breathable and comfortable':
        'with mesh underlays throughout the upper, these lightweight sneakers allow your feet to breathe so you can stay comfortable wearing them Morning to night. Multiple underlays and overlays bring depth to the shoe',
      'upgraded retro style':
        "featuring the classic n logo and style-specific branding on the tongue, these retro sneakers bring NB heritage to your shoe closet. Enjoy a traditional '90s silhouette with modern comfort elements",
      'go-to daily sneaker':
        'whether worn with your favorite jeans, sweatpants or shorts, these comfortable shoes make great daily sneakers. The clean lines and attractive shape bring elevated style to all your day-to-day looks',
    },
  },
  {
    id: 77,
    url: 'https://www.amazon.co.uk/dp/B08YZ13TCC',
    title: "GIOSEPPO Women's Slidre Sneaker",
    price: 75.7,
    brand: 'GIOSEPPO',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41Ftgd6hoML.jpg',
      'https://m.media-amazon.com/images/I/41iE02kIBeL.jpg',
      'https://m.media-amazon.com/images/I/413ME60z2XL.jpg',
      'https://m.media-amazon.com/images/I/31wb9pISHtL.jpg',
      'https://m.media-amazon.com/images/I/41HbG--mm9L.jpg',
      'https://m.media-amazon.com/images/I/41J1xKjbcvL.jpg',
      'https://m.media-amazon.com/images/I/41Gx+cWOhxL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Polyester',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 78,
    url: 'https://www.amazon.co.uk/dp/B087D1LCGK',
    title: "The Children's Place Unisex-Child Bow Strap Ballet Flats",
    price: 35.22,
    brand: "The Children's Place",
    categoryId: 49,
    images: [
      'https://m.media-amazon.com/images/I/41YC+aTNoSL.jpg',
      'https://m.media-amazon.com/images/I/41jbG9YKU7L.jpg',
      'https://m.media-amazon.com/images/I/416HHcYBJuL.jpg',
      'https://m.media-amazon.com/images/I/41y+7+ogYIL.jpg',
      'https://m.media-amazon.com/images/I/41hPKtebEbL.jpg',
      'https://m.media-amazon.com/images/I/41LxqHF7q4L.jpg',
      'https://m.media-amazon.com/images/I/41NIK8+lY4L.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Pull On',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 79,
    url: 'https://www.amazon.co.uk/dp/B07C3V192T',
    title:
      'Silver_river Girls Sandals Closed Toe Summer Brethable Flat Mesh Shoes Beach Shoes Princess Shoes',
    price: 31.02,
    brand: 'Silver_river',
    categoryId: -1,
    images: [
      'https://m.media-amazon.com/images/I/41QPvgtuLQL.jpg',
      'https://m.media-amazon.com/images/I/51SXpC7W3FL.jpg',
      'https://m.media-amazon.com/images/I/51zwhGyJBwL.jpg',
      'https://m.media-amazon.com/images/I/51MZveY1wdL.jpg',
      'https://m.media-amazon.com/images/I/51yTNTIwDTL.jpg',
      'https://m.media-amazon.com/images/I/518nxIkJJcL.jpg',
    ],
    features: {
      'outer material': 'leather, mesh',
      padding: 'fabric',
      'outer Material': 'Synthetic',
      sole: 'Leather',
      closure: 'Velcro',
      'heel Height': '1.5 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
      'sole material': 'synthetic tico',
      'heel type': 'flat',
    },
  },
  {
    id: 80,
    url: 'https://www.amazon.co.uk/dp/B084V82Z4P',
    title: "chicco Boy's Scarpa Cecco Gymnastics Shoes",
    price: 113.33,
    brand: 'chicco',
    categoryId: 43,
    images: [
      'https://m.media-amazon.com/images/I/4199IaBkxxL.jpg',
      'https://m.media-amazon.com/images/I/41q5iivusIL.jpg',
      'https://m.media-amazon.com/images/I/41vHajMjg0L.jpg',
      'https://m.media-amazon.com/images/I/31Sr4MWYurL.jpg',
      'https://m.media-amazon.com/images/I/41COP2s-1uL.jpg',
      'https://m.media-amazon.com/images/I/41D9Eq1yHWL.jpg',
      'https://m.media-amazon.com/images/I/412pTuUOnWL.jpg',
    ],
    features: {
      'outer Material': 'Fabric',
      'inner Material': 'Manmade',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Hook & Loop',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 81,
    url: 'https://www.amazon.co.uk/dp/B01H8PTWHG',
    title: "Vibram FiveFingers Women's V-Train Sneakers",
    price: 72.81,
    brand: 'Visit the Vibram FiveFingers Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41Qc3C0gn3L.jpg',
      'https://m.media-amazon.com/images/I/51Pg1CACYNL.jpg',
      'https://m.media-amazon.com/images/I/51nc+kCRboL.jpg',
      'https://m.media-amazon.com/images/I/41bZ+kxtyrL.jpg',
      'https://m.media-amazon.com/images/I/416f6bnkKBL.jpg',
      'https://m.media-amazon.com/images/I/41tD85si9+L.jpg',
      'https://m.media-amazon.com/images/I/41rx1dScu-L.jpg',
    ],
    features: {
      'care Instructions': 'Machine wash cold air dry',
      'outer Material': 'Fabric',
      'inner Material': 'Textile',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 82,
    url: 'https://www.amazon.co.uk/dp/B071HBYHQL',
    title: "ECCO Men's Offroad Hiking Sandals",
    price: 31.63,
    brand: 'Visit the ECCO Store',
    categoryId: 50,
    images: [
      'https://m.media-amazon.com/images/I/41M6vFDgXoL.jpg',
      'https://m.media-amazon.com/images/I/41CGNwP4zBL.jpg',
      'https://m.media-amazon.com/images/I/41ZwiHqlUrL.jpg',
      'https://m.media-amazon.com/images/I/31EFGAwapSL.jpg',
      'https://m.media-amazon.com/images/I/31WRZZZa-eL.jpg',
      'https://m.media-amazon.com/images/I/31phKhyz67L.jpg',
      'https://m.media-amazon.com/images/I/41Fx5xulj-L.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Synthetic Fabric',
      sole: 'Bast',
      closure: 'Hook & Loop',
      'heel Height': '2 centimetres',
      'heel Type': 'Flat',
      'material Composition': '',
      'fit Type': 'Regular size',
      'shaft Diameter': 'Verstellbar',
      'shoe Width': 'Normal mens_us, Normal unisex_eu',
      'has removable insert': 'False',
    },
  },
  {
    id: 83,
    url: 'https://www.amazon.co.uk/dp/B07B9N3FKX',
    title:
      "Merrell Men's Yokota 2 MID Waterproof Hiking Boot, Bracken, 10 W US",
    price: 79.52,
    brand: 'Visit the Merrell Store',
    categoryId: 15,
    images: [
      'https://m.media-amazon.com/images/I/411CN8JkVML.jpg',
      'https://m.media-amazon.com/images/I/41eKlnW53-L.jpg',
      'https://m.media-amazon.com/images/I/41HIVFaR5-L.jpg',
      'https://m.media-amazon.com/images/I/310K3daIqtL.jpg',
      'https://m.media-amazon.com/images/I/319LSsbxvpL.jpg',
      'https://m.media-amazon.com/images/I/4172PtWNzkL.jpg',
      'https://m.media-amazon.com/images/I/41J7TGjCx4L.jpg',
    ],
    features: {
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Height': '1.5 inches',
      'heel Type': 'low-heel',
      'shoe Width': 'W',
    },
  },
  {
    id: 84,
    url: 'https://www.amazon.co.uk/dp/B07KMBKYNP',
    title: "Merrell Men's Alpine Sneaker",
    price: 98.95,
    brand: 'Visit the Merrell Store',
    categoryId: 14,
    images: [
      'https://m.media-amazon.com/images/I/41jXd-oaiML.jpg',
      'https://m.media-amazon.com/images/I/41mx1ERobEL.jpg',
      'https://m.media-amazon.com/images/I/31mPNGYpDpL.jpg',
      'https://m.media-amazon.com/images/I/31tC61iMUeL.jpg',
      'https://m.media-amazon.com/images/I/31JDefaT9JL.jpg',
      'https://m.media-amazon.com/images/I/3109Ps11ylL.jpg',
      'https://m.media-amazon.com/images/I/410NyurnIgL.jpg',
    ],
    features: {
      'outer Material': 'Fabric,Leather - Suede',
      'inner Material': 'Fabric',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Height': '1 inches',
      'heel Type': 'low-heel',
      'shoe Width': 'M',
    },
  },
  {
    id: 85,
    url: 'https://www.amazon.co.uk/dp/B08HZBWJNB',
    title: "Pantofola d’Oro Women's Ala Low Oxford Flat",
    price: 58.49,
    brand: 'Pantofola d’Oro',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41oMN9JSnCL.jpg',
      'https://m.media-amazon.com/images/I/413K1pO5IsL.jpg',
      'https://m.media-amazon.com/images/I/41ye3255ScL.jpg',
      'https://m.media-amazon.com/images/I/211TcMHtlwL.jpg',
      'https://m.media-amazon.com/images/I/41OIysBC40L.jpg',
      'https://m.media-amazon.com/images/I/41HMQJzq1fL.jpg',
      'https://m.media-amazon.com/images/I/41h+ulChrkL.jpg',
    ],
    features: {
      'outer Material': 'Suede',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 86,
    url: 'https://www.amazon.co.uk/dp/B08BWS9KLH',
    title: 'adidas Unisex Freak .4 Tf J Football Shoe',
    price: 57.44,
    brand: 'Visit the adidas Store',
    categoryId: 51,
    images: [
      'https://m.media-amazon.com/images/I/41tBahr80aL.jpg',
      'https://m.media-amazon.com/images/I/51d00reeqqL.jpg',
      'https://m.media-amazon.com/images/I/416bAzBM34L.jpg',
      'https://m.media-amazon.com/images/I/41teNl6MeyL.jpg',
      'https://m.media-amazon.com/images/I/41lJzQMN2SL.jpg',
      'https://m.media-amazon.com/images/I/41chuYbhm+L.jpg',
      'https://m.media-amazon.com/images/I/41JVCsUluzL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 87,
    url: 'https://www.amazon.co.uk/dp/B09BRDSFQT',
    title:
      'Unisex Slip on Sneakers Fashion Casual Breathable Sneakers Lightweight and Comfortable Flat-bottomed Sneakers Outdoor Fitness Sneakers Walking Shoes Jogging Casual Shoes Size 35-44',
    price: 66.71,
    brand: 'WQEQ',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41SQjUvXqgS.jpg',
      'https://m.media-amazon.com/images/I/51DeTOD6wFS.jpg',
      'https://m.media-amazon.com/images/I/510suC8WO6S.jpg',
      'https://m.media-amazon.com/images/I/51lHIp4lm7S.jpg',
      'https://m.media-amazon.com/images/I/51VNIIF5qsS.jpg',
      'https://m.media-amazon.com/images/I/41U-9z4qS2S.jpg',
    ],
    features: {
      material:
        'The material of the summer men / women sports shoes is light and breathable, vamp with a certain elasticity and good winding properties, which is suitable for different types of feet. The breathable fabric is well ventilated and does not have an unpleasant odor. The appearance is simple and fashionable and can be combined with different styles of clothing.',
      sole: 'This cushioning men / women running shoes has a soft rubber sole. The ergonomic design allows the shoe to conform to the foot and make it more comfortable to wear. The soft rubber sole can slow down the impact of the foot during exercise or normal wearing, bring you a good wearing experience, and reduce the risk of injury.',
      'outer Material': 'Synthetic',
      closure: 'Slip On',
      'shoe Width': 'Medium',
      occasion:
        'Since these men / women sports shoes are light and breathable, they are more suitable for wearing in spring, summer and autumn. The design style is relatively casual and simple, suitable for indoor fitness and everyday life. Due to the soft sole, it is recommended that you choose a flat road when jogging outdoors to avoid foot injuries.',
      'quality Service':
        'If you have any questions about our shoes, please feel free to contact me. I will provide you with the best service and wish you a happy life!',
      reminder:
        'Please check the size chart carefully when purchasing, as Asian sizes are different from European and American sizes, please check the size chart carefully.',
    },
  },
  {
    id: 88,
    url: 'https://www.amazon.co.uk/dp/B0813LT3JN',
    title: "Icebug Pace 3 M Michelin WIC GTX Men's Outdoor Shoes",
    price: 97.75,
    brand: 'Icebug',
    categoryId: 52,
    images: ['https://m.media-amazon.com/images/I/41KMteBuCiL.jpg'],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Rubber',
      closure: 'Lacing.',
      'shoe Width': 'Schmal',
      outsoles: 'Michelin Wic winter rubber',
    },
  },
  {
    id: 89,
    url: 'https://www.amazon.co.uk/dp/B081629JXT',
    title: 'TOMS Women Sicily Sandals',
    price: 111.66,
    brand: 'Visit the TOMS Store',
    categoryId: 53,
    images: [
      'https://m.media-amazon.com/images/I/41r9-Hzlq4L.jpg',
      'https://m.media-amazon.com/images/I/31vrJFB8leL.jpg',
      'https://m.media-amazon.com/images/I/31vA4oCnIVL.jpg',
      'https://m.media-amazon.com/images/I/21zzizYyH4L.jpg',
      'https://m.media-amazon.com/images/I/311dhd7HKvL.jpg',
    ],
    features: {
      'outer Material': 'Canvas',
      sole: 'Suede',
      closure: 'Pull On',
      'heel Height': '1 centimetres',
      'heel Type': 'Flat',
      'shoe Width': 'Normale',
    },
  },
  {
    id: 90,
    url: 'https://www.amazon.co.uk/dp/B0873ZLX5Z',
    title: "Kappa Unisex's Authentic 222 Banda Mitel 1 Track Shoe",
    price: 84.84,
    brand: 'Visit the Kappa Store',
    categoryId: 16,
    images: [
      'https://m.media-amazon.com/images/I/41Tylmuc7vL.jpg',
      'https://m.media-amazon.com/images/I/51zAwYzh9PL.jpg',
      'https://m.media-amazon.com/images/I/41iwiio661L.jpg',
      'https://m.media-amazon.com/images/I/31cI3FfdmFL.jpg',
      'https://m.media-amazon.com/images/I/41t2xwdpDCL.jpg',
      'https://m.media-amazon.com/images/I/31p9cgvREfL.jpg',
      'https://m.media-amazon.com/images/I/41mTQEBy7RL.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 91,
    url: 'https://www.amazon.co.uk/dp/B08QML4C2Y',
    title:
      "Dancing Shoes Women's Peep Toe Sparkle Rhinestones Tango Ballroom Latin Modern Dance Shoes Evening Wedding Sandals (Color : Slip on Beige 7 5cm Heel, Size : 3 UK)",
    price: 20.98,
    brand: 'Dancing Shoes',
    categoryId: 21,
    images: [
      'https://m.media-amazon.com/images/I/41qp2MDbMLL.jpg',
      'https://m.media-amazon.com/images/I/51+Op08ph1L.jpg',
      'https://m.media-amazon.com/images/I/41XSW0SRIiL.jpg',
      'https://m.media-amazon.com/images/I/419Qd78tflL.jpg',
      'https://m.media-amazon.com/images/I/41sF-eFzBSL.jpg',
    ],
    features: {
      'outer Material': 'Satin or glitter synthetic as the picture shows',
      'inner Material': 'Manmade',
    },
  },
  {
    id: 92,
    url: 'https://www.amazon.co.uk/dp/B099RPDR4L',
    title:
      "Roller skates, for Young Girl Running Shoes Sports Shoes Kids Skateboard Shoes Children's Shoes With Skate Shoes Trainer Sneakers Roll Shoes (Color : Weiß, Size : Einzelrad-32)",
    price: 113.95,
    brand: 'SXDYJ',
    categoryId: 55,
    images: [
      'https://m.media-amazon.com/images/I/51c5nhqjiuL.jpg',
      'https://m.media-amazon.com/images/I/41GIxPxqsDL.jpg',
      'https://m.media-amazon.com/images/I/511uxzNvROL.jpg',
      'https://m.media-amazon.com/images/I/417ZKRnHljL.jpg',
    ],
    features: {
      '2-in-1 rolling boots':
        'Adjustable multifunctional rolling boots differ from conventional roller skates on the market. The hidden wheels can be after hiding like normal sports shoes so they can adjust roller skates. Ice skates can not only run skates, but also.',
      'high quality material':
        'The multifunctional adjustable roller skates have a comfortable and breathable upper and shoe lining, wear-resistant soles and good elasticity. We do not pay attention to the carrying capacity of the wheels, but also on the material selection of the upper material to produce high-quality roller skates.',
      'hidden Cycles':
        'Roller shoes can appear through a button on the heel and hide the role. So you can use both rolling boots and normal sports shoes.',
      'slip resistance':
        'Cycles with good grip improve the slip resistance of the tire by imitation of the sawtooth function of the roller. Make the stability and safety of the movement safe. Use conventional shoelaces like sneakers to optimally set the laces optimally.',
      'special Gift':
        'Roller is also one of the most traditional recreational sports, which is ideal for skating / party / disco / dance / birthday / christmas. On weekends you can play with your friends or children or give them away as a Christmas present.',
    },
  },
  {
    id: 93,
    url: 'https://www.amazon.co.uk/dp/B08KW66C1Z',
    title: "Conguitos Girl's Mirror Slide Sandal",
    price: 31.25,
    brand: 'Conguitos',
    categoryId: 20,
    images: ['https://m.media-amazon.com/images/I/31DJNXzbawL.jpg'],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Manmade',
      sole: 'Rubber',
      closure: 'Buckle',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 94,
    url: 'https://www.amazon.co.uk/dp/B089NWG8XF',
    title: "s.Oliver Women's 5-5-33206-36 100 Sneaker",
    price: 54.07,
    brand: 'Visit the s.Oliver Store',
    categoryId: -1,
    images: [
      'https://m.media-amazon.com/images/I/31gL-eHLG4S.jpg',
      'https://m.media-amazon.com/images/I/31-HW7J7hpS.jpg',
      'https://m.media-amazon.com/images/I/41HPyvwMqyS.jpg',
      'https://m.media-amazon.com/images/I/31lXSCZdOSS.jpg',
      'https://m.media-amazon.com/images/I/31mM2c5kL-S.jpg',
      'https://m.media-amazon.com/images/I/31zoYQEP1ES.jpg',
      'https://m.media-amazon.com/images/I/31s1KB7GB5S.jpg',
    ],
    features: {
      'outer Material': 'Synthetic',
      'inner Material': 'Textile',
      sole: 'Synthetic',
      closure: 'Hook & Loop',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 95,
    url: 'https://www.amazon.co.uk/dp/B01HDNXK3U',
    title: 'Samuel Hubbard Mens Hubbard Free UN-Sneaker Oxford',
    price: 66.65,
    brand: 'Samuel Hubbard',
    categoryId: 25,
    images: [
      'https://m.media-amazon.com/images/I/41LBEwPq1fL.jpg',
      'https://m.media-amazon.com/images/I/41rtI0Jz+GL.jpg',
      'https://m.media-amazon.com/images/I/41hAIrACISL.jpg',
      'https://m.media-amazon.com/images/I/41uX5JvjMgL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      sole: 'Leather',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'D(M) mens_us',
    },
  },
  {
    id: 96,
    url: 'https://www.amazon.co.uk/dp/B07P6FJHHF',
    title: "Rieker Women's Damen Halbschuhe 53715 Low Shoes",
    price: 111.09,
    brand: 'Rieker',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41zqUVhYIFL.jpg',
      'https://m.media-amazon.com/images/I/41ZKHO54CKL.jpg',
      'https://m.media-amazon.com/images/I/41wLI+ZjcIL.jpg',
      'https://m.media-amazon.com/images/I/414MEcjECWL.jpg',
      'https://m.media-amazon.com/images/I/41+X8gBJPcL.jpg',
    ],
    features: {
      'outer Material': 'N / A',
      'inner Material': 'Manmade',
      sole: 'Ethylene Vinyl Acetate',
      closure: 'Zip',
      'heel Height': '1 centimetres',
      'heel Type': 'West',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 97,
    url: 'https://www.amazon.co.uk/dp/B079V143HZ',
    title: "Däumling Unisex's Alfi Classic Boots",
    price: 83.62,
    brand: 'Däumling',
    categoryId: 45,
    images: [
      'https://m.media-amazon.com/images/I/41-A8ilQYoL.jpg',
      'https://m.media-amazon.com/images/I/41IHi-AxkjL.jpg',
      'https://m.media-amazon.com/images/I/31Ic3afrAsL.jpg',
      'https://m.media-amazon.com/images/I/31b0GbabFOL.jpg',
      'https://m.media-amazon.com/images/I/31Z4X3NDAAL.jpg',
      'https://m.media-amazon.com/images/I/41geulVjZYL.jpg',
      'https://m.media-amazon.com/images/I/41PoxRfJTKL.jpg',
    ],
    features: {
      'outer Material': 'Leather',
      'inner Material': 'Manmade',
      sole: 'Synthetic',
      closure: 'Lace-Up',
      'heel Type': 'Flat',
      'shoe Width': 'Schmal',
    },
  },
  {
    id: 98,
    url: 'https://www.amazon.co.uk/dp/B088KVB7G4',
    title: "Reebok Women's Advanced Trainette Cross Trainer",
    price: 49.93,
    brand: 'Visit the Reebok Store',
    categoryId: 56,
    images: [
      'https://m.media-amazon.com/images/I/41sOSE40H2L.jpg',
      'https://m.media-amazon.com/images/I/410uGVjN3YL.jpg',
      'https://m.media-amazon.com/images/I/413Tc+RIh1L.jpg',
      'https://m.media-amazon.com/images/I/31idPaXJDpL.jpg',
      'https://m.media-amazon.com/images/I/31nwJ26cfEL.jpg',
      'https://m.media-amazon.com/images/I/318YRzUdpGL.jpg',
      'https://m.media-amazon.com/images/I/41IF9CHgi2L.jpg',
    ],
    features: {
      'designed for': 'Boot camps and high-intensity workouts',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'No Heel',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 99,
    url: 'https://www.amazon.co.uk/dp/B0064LF8P6',
    title: "Gola Classics Women's Quattro Trainer",
    price: 80.13,
    brand: 'Visit the Gola Store',
    categoryId: 6,
    images: [
      'https://m.media-amazon.com/images/I/41pPmVSfeTL.jpg',
      'https://m.media-amazon.com/images/I/41lM73k2llL.jpg',
      'https://m.media-amazon.com/images/I/41pcoqZ6rlL.jpg',
      'https://m.media-amazon.com/images/I/31uQF3OHdVL.jpg',
      'https://m.media-amazon.com/images/I/31S0+RF61lL.jpg',
      'https://m.media-amazon.com/images/I/31IMwYdvrLL.jpg',
      'https://m.media-amazon.com/images/I/31iB9Oya2tL.jpg',
    ],
    features: {
      'outer Material': 'Canvas',
      'inner Material': 'Textile',
      sole: 'Rubber',
      closure: 'Lace-Up',
      'heel Type': 'Low',
      'shoe Width': 'Medium',
    },
  },
  {
    id: 100,
    url: 'https://www.amazon.co.uk/dp/B00LVSW3LE',
    title: 'Scholl Slippers Sun',
    price: 98.25,
    brand: 'Visit the Scholl Store',
    categoryId: 58,
    images: ['https://m.media-amazon.com/images/I/31KcVEzMJpL.jpg'],
    features: {
      'outer Material': 'Synthetic',
      sole: 'Manmade',
      closure: 'Pull On',
      'heel Height': '25 millimetres',
      'heel Type': 'Block',
      'shoe Width': 'Medium',
    },
  },
]
